name: Release Workflow

on:
  push:
    tags:
      - 'v*'  # Execute when tags are created
  
  # Allow manual execution
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to npm'
        required: true
        type: boolean
        default: false

# Add permissions at workflow level
permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Build
        run: npm run build

      # Get version from tag
      - name: Get version from tag
        if: github.event_name == 'push'
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Show version
        run: |
          echo "Version to use: $VERSION"

      - name: Update package.json version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          npm version $VERSION --no-git-tag-version
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add package.json
          git commit -m "chore: update package version to $VERSION [skip ci]"
          git push origin HEAD:main

      - name: Update README badges
        run: |
          ./bin/update_myself.sh
          if [[ -n $(git status --porcelain README.md) ]]; then
            echo "README.md has changes. Committing."
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add README.md
            git commit -m "docs: update version badges [skip ci]"
            git push origin HEAD:main
          fi

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v') || inputs.publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 