name: Update Version Information

on:
  push:
    tags:
      - 'v*'  # タグが作成されたときに実行
  
  # 手動実行も可能に
  workflow_dispatch:
    inputs:
      version:
        description: '更新するバージョン（指定しない場合はpackage.jsonから取得）'
        required: false
        type: string

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # タグ情報を取得するため全履歴を取得
          ref: ${{ github.event.ref || 'main' }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Get version
        id: get-version
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            # 手動実行時に指定されたバージョンを使用
            VERSION="${{ github.event.inputs.version }}"
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            # タグからバージョンを取得
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"
          else
            # package.jsonからバージョンを取得
            VERSION=$(node -p "require('./package.json').version")
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "バージョン: $VERSION"
      
      - name: Update README badges
        run: |
          chmod +x bin/update_myself.sh
          ./bin/update_myself.sh
          
      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain README.md)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Get branch name
        id: branch-name
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "branch=main" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # 明示的にブランチを作成してチェックアウト
          git checkout -b update-readme
          git add README.md
          git commit -m "docs: READMEのバージョン表示を ${{ steps.get-version.outputs.version }} に更新 [skip ci]"
          # 明示的なターゲットブランチを指定してプッシュ
          git push -f origin update-readme:${{ steps.branch-name.outputs.branch }} 